#
# EPITECH PROJECT, 2021
# Epitech Years 3
# File description:
# Dockerfile.standalone
#

FROM gcc:11.2
SHELL ["/bin/bash", "-c"]
WORKDIR /app/

COPY . .

RUN ./befunge-compile.sh

CMD [ "./compiled-app" ]