#
# EPITECH PROJECT, 2021
# Epitech Years 3
# File description:
# Dockerfile.standalone
#

FROM node:14.17.5-alpine
RUN apk add --no-cache bash

SHELL ["/bin/bash", "-c"]
WORKDIR /app/

COPY . .

RUN npm install

CMD [ "node", "." ]